// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Glv0qGoHHtg2Zqbi_aPj6bFFs5rHjMI',
    appId: '1:822214741718:web:5e52efe27a5417dd8c4377',
    messagingSenderId: '822214741718',
    projectId: 'steps-tracker-f9a37',
    authDomain: 'steps-tracker-f9a37.firebaseapp.com',
    storageBucket: 'steps-tracker-f9a37.appspot.com',
    measurementId: 'G-8V18E44M68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnW0YekqJTqo1cYCJSM8CrhCz-m1wyAxQ',
    appId: '1:822214741718:android:b56a82498305a0098c4377',
    messagingSenderId: '822214741718',
    projectId: 'steps-tracker-f9a37',
    storageBucket: 'steps-tracker-f9a37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsnf5j2AKla5KE6YQT3vsQeSCXo3E601U',
    appId: '1:822214741718:ios:d93a2b3d634a58fe8c4377',
    messagingSenderId: '822214741718',
    projectId: 'steps-tracker-f9a37',
    storageBucket: 'steps-tracker-f9a37.appspot.com',
    iosBundleId: 'com.example.stepsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsnf5j2AKla5KE6YQT3vsQeSCXo3E601U',
    appId: '1:822214741718:ios:72a338e4889f74148c4377',
    messagingSenderId: '822214741718',
    projectId: 'steps-tracker-f9a37',
    storageBucket: 'steps-tracker-f9a37.appspot.com',
    iosBundleId: 'com.example.stepsTracker.RunnerTests',
  );
}
